### PR TITLE
bug: fix safari bug

### LINKED ISSUE #11: safari bug
Bug in Safari 13 is causing the storageEvent to be fired on a single tab despite the [MDN documentation ](https://developer.mozilla.org/en-US/docs/Web/API/StorageEvent) specifying that `StorageEvent` only gets triggered when another window changes `Storage`.

This [stack overflow](https://stackoverflow.com/questions/61269238/safari-fires-storageevent-in-same-tab?fbclid=IwAR1MwrrNATC4WDF4OowzfFpbo97wb0XGzEY2S6pQN9Hn02WjB5ah1ss8XbU) and this [bug report](https://bugs.webkit.org/show_bug.cgi?id=210512) cover the details.

Suggested change:
Check if the canvas is in focus.

### PR DESCRIPTION
**Pull request by BryanPan342**
remove bug that was for some reason locking when storage was being updated

Fixes: #11

### CODE REVIEW

File: src/components/Paint.tsx [hunk 1]
```diff
@@ -84,12 +84,9 @@ function Paint(props: PaintProps) {
 
     const storageHandler = (e: StorageEvent) => {
         if (e.key == 'stack' && !selfStore) {
-            debug('different instance wrote to local storage; locking');
+            debug('different instance wrote to local storage');
             setSelfStore(false);
             // setStack(JSON.parse(e.newValue) || []);
-            setCannotDraw(true);
-            setCanUndo(false);
-            setCanToggle(false);
```
Comment (arjunr00) [inline src/components/Paint.tsx:92]: So this code is in place so that a single user can't open multiple instances of the website and draw from all of them--that's why the draw controls lock. That's what `selfStore` is for---if instance A detects that local storage has updated but `selfStore` is false, that means there's another instance B on the computer that drew a stroke, so instance A locks its controls.

**Review by arjunr00 — DISMISSED** [review]

File: src/components/Paint.tsx (hunk 1 above)
Comment (BryanPan342) [reply src/components/Paint.tsx:92]: basically it kept getting locked for some reason.. im not entirely sure why.. im assuming the !selfStore wasn't being set properly?

Comment (BryanPan342) [reply src/components/Paint.tsx:92]: wait why is this function necessary.. the storage should be the same no?

Comment (arjunr00) [reply src/components/Paint.tsx:92]: Hmm maybe, I'll take a look on my Macbook and see if I can figure anything out

**Comment by BryanPan342** [comment]
https://github.com/UCLA-Creative-Labs/agora-gaia/blob/1f7e92ff5686747785a43374859e880ec1590dab/src/components/Paint.tsx#L123-L139

this hook SOMETIMES gets called on after component mount of the storage handler:
https://github.com/UCLA-Creative-Labs/agora-gaia/blob/e97c74386cd6cb71776134de5e8931d6816b27fb/src/components/Paint.tsx#L105

i.e. the payload gets way too big to the point where it the component mounts before the stack is set.. we should add a flag in the storage handler for this

**Review by arjunr00 — APPROVED** [review]
I'll take your word that this fixes Safari since I had trouble loading it on my Mac, but LGTM otherwise.
